/**
 * Agent registration — ensures memory_stores row, Qdrant collection, and memory_code.
 *
 * Run once per agent via RegisterAgent gRPC or scripts/register-demo-agent.js.
 * memory_code is generated by LLM from the agent system prompt + enabled types.
 */
import { config } from "../config.js";
import { listRegisteredAgents, loadAgentPrompt, resolveAgentPrompt } from "../agents/agent-prompts.js";

class AgentSetupService {
  constructor(postgres, promptGenerator, qdrant = null) {
    this.postgres = postgres;
    this.promptGenerator = promptGenerator;
    this.qdrant = qdrant;
  }
  postgres;
  promptGenerator;
  qdrant;

  /**
   * Register one agent: postgres store row, Qdrant collection, LLM memory_code.
   * @returns {{ memoryCodeGenerated: boolean, collectionName: string | null }}
   */
  async registerAgent(input) {
    const systemPrompt = resolveAgentPrompt(input.agentId, input.systemPrompt);
    if (!systemPrompt) {
      throw new Error(
        `No system prompt for "${input.agentId}". Pass systemPrompt or register in agent-prompts.js`
      );
    }
    if (this.postgres) {
      await this.postgres.ensureAgentStore(input.agentId, systemPrompt);
    }
    let collectionName = null;
    if (this.qdrant) {
      collectionName = await this.qdrant.ensureCollection(input.agentId);
    }
    await this.promptGenerator.generateMemoryCode({
      agentId: input.agentId,
      systemPrompt,
      typesEnabled: config.memory.typesEnabled
    });
    return { memoryCodeGenerated: true, collectionName };
  }

  /** Register all agents listed in agent-prompts.js. */
  async registerAllFromRegistry() {
    for (const agentId of listRegisteredAgents()) {
      const systemPrompt = loadAgentPrompt(agentId);
      if (!systemPrompt) continue;
      await this.registerAgent({ agentId, systemPrompt });
      console.log(`[setup] ${agentId} — memory_code ok`);
    }
  }
}

export {
  AgentSetupService
};
